//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThunderITforGEA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspNetUsers
    {
        public AspNetUsers()
        {
            this.SprzetUzytkownika = new HashSet<SprzetUzytkownika>();
            this.Historia = new HashSet<Historia>();
        }
    
        public string Id { get; set; }
        public bool EmailConfirmed { get; set; }
        public string PasswordHash { get; set; }
        public string SecurityStamp { get; set; }
        public string PhoneNumber { get; set; }
        public bool PhoneNumberConfirmed { get; set; }
        public bool TwoFactorEnabled { get; set; }
        public Nullable<System.DateTime> LockoutEndDateUtc { get; set; }
        public bool LockoutEnabled { get; set; }
        public int AccessFailedCount { get; set; }
        public string UserName { get; set; }
        public string login { get; set; }
        public string imie { get; set; }
        public string nazwisko { get; set; }
        public string firma { get; set; }
        public string adres { get; set; }
        public string miasto { get; set; }
        public string kraj { get; set; }
        public string telefon { get; set; }
        public string Email { get; set; }
        public string segment { get; set; }
        public string stanowisko { get; set; }
        public Nullable<System.DateTime> ostatnia_modifykacja { get; set; }
        public string segment2 { get; set; }
        public Nullable<int> iloscDniBezlogowania { get; set; }
        public string pierwszyLogin { get; set; }
        public string jezyk { get; set; }
    
        public virtual ICollection<SprzetUzytkownika> SprzetUzytkownika { get; set; }
        public virtual ICollection<Historia> Historia { get; set; }
    }
}
