//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThunderITforGEA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Segmenty
    {
        public string id_s { get; set; }
        public string nazwa { get; set; }
    }
}
